locations = ['Venice', 'Iceland', 'California', 'Moscow', 'Thailand', 'France']
print(locations)
print(sorted(locations))
print(sorted(locations, reverse=True))
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)